sonar.projectKey = Joaquin_Lopez_t1
sonar.python.version = 3.13

sonar.sources=apps
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.*/**

sonar.modules = producer,consumer

producer.sonar.projectName=lab8-producer
producer.sonar.sources=app
producer.sonar.tests=tests
producer.sonar.python.coverage.reportPaths=coverage.xml

consumer.sonar.projectName=lab8-consumer
consumer.sonar.sources=app
consumer.sonar.tests=tests
consumer.sonar.python.coverage.reportPaths=coverage.xml

sonar.host.url = ${SONAR_HOST_URL}
sonar.token = ${SONAR_TOKEN}
